package com.ikasle.scrollkill.ui.theme

import androidx.compose.ui.graphics.Color

// Scroll Kill brand palette. Focus / digital-wellbeing tone: a deep teal primary
// with a warm amber accent on neutral slate surfaces. Fixed scheme, no Material You
// dynamic color, so the identity stays consistent across devices.

// --- Light ---
val LightPrimary = Color(0xFF00695C)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFA7F3E4)
val LightOnPrimaryContainer = Color(0xFF00201B)
val LightSecondary = Color(0xFF4A635D)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFCCE8E1)
val LightOnSecondaryContainer = Color(0xFF06201B)
val LightTertiary = Color(0xFFB26A00)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFFFDDB5)
val LightOnTertiaryContainer = Color(0xFF2A1800)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFF8FAF8)
val LightOnBackground = Color(0xFF191C1B)
val LightSurface = Color(0xFFF8FAF8)
val LightOnSurface = Color(0xFF191C1B)
val LightSurfaceVariant = Color(0xFFDBE5E1)
val LightOnSurfaceVariant = Color(0xFF3F4946)
val LightOutline = Color(0xFF6F7975)
val LightOutlineVariant = Color(0xFFBFC9C4)
val LightInverseSurface = Color(0xFF2E3130)
val LightInverseOnSurface = Color(0xFFEFF1EF)
val LightInversePrimary = Color(0xFF55DBC4)
val LightScrim = Color(0xFF000000)

// --- Dark ---
val DarkPrimary = Color(0xFF55DBC4)
val DarkOnPrimary = Color(0xFF003730)
val DarkPrimaryContainer = Color(0xFF005046)
val DarkOnPrimaryContainer = Color(0xFF76F8E0)
val DarkSecondary = Color(0xFFB1CCC4)
val DarkOnSecondary = Color(0xFF1C352F)
val DarkSecondaryContainer = Color(0xFF334B45)
val DarkOnSecondaryContainer = Color(0xFFCCE8E1)
val DarkTertiary = Color(0xFFFFB868)
val DarkOnTertiary = Color(0xFF472A00)
val DarkTertiaryContainer = Color(0xFF663E00)
val DarkOnTertiaryContainer = Color(0xFFFFDDB5)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF191C1B)
val DarkOnBackground = Color(0xFFE1E3E0)
val DarkSurface = Color(0xFF191C1B)
val DarkOnSurface = Color(0xFFE1E3E0)
val DarkSurfaceVariant = Color(0xFF3F4946)
val DarkOnSurfaceVariant = Color(0xFFBFC9C4)
val DarkOutline = Color(0xFF899390)
val DarkOutlineVariant = Color(0xFF3F4946)
val DarkInverseSurface = Color(0xFFE1E3E0)
val DarkInverseOnSurface = Color(0xFF2E3130)
val DarkInversePrimary = Color(0xFF00695C)
val DarkScrim = Color(0xFF000000)
